### PR TITLE
:bug: Fix user cant submit existing token when editing name only

### LINKED ISSUE #18: Editing token name doesn't allow submit until switched to value input
https://github.com/user-attachments/assets/2c0aeeae-7041-4c64-827b-5af01405b641

When editing a token the user has to switch to the value field for the name change to be valid.

## Steps to reproduce

1. Edit an existing token
2. Update the name
3. Submit should be not `disabled` when name is valid

### PR DESCRIPTION
**Pull request by floscr**
- Fixes https://github.com/tokens-studio/penpot/issues/18
- Adds integration test for editing a token

### CODE REVIEW

**Review by not-in-stock — APPROVED** [review]
LGTM!

File: frontend/src/app/main/ui/workspace/tokens/form.cljs [hunk 1]
```diff
@@ -389,6 +391,22 @@
...
+     (fn []
+       (reset! form-token-cache-atom nil)))
+
+    ;; Update the value when editing an existing token
+    ;; so the user doesn't have to interact with the form to validate the token
+    (mf/use-effect
+     (mf/deps create? resolved-tokens token token-resolve-result set-resolve-value)
+     (fn []
+       (when (and (not create?)
+                  (not @token-resolve-result)
```
Comment (EvaMarco) [inline frontend/src/app/main/ui/workspace/tokens/form.cljs]: Make deref of this state on let, and not @ on every use.

File: frontend/src/app/main/ui/workspace/tokens/form.cljs [hunk 2]
```diff
@@ -389,6 +391,22 @@
...
+                  resolved-tokens)
+         (-> (get resolved-tokens @name-ref)
```
Comment (EvaMarco) [inline frontend/src/app/main/ui/workspace/tokens/form.cljs:407]: The same as above

File: frontend/playwright/ui/specs/tokens.spec.js [hunk 3]
```diff
@@ -156,7 +235,7 @@ test.describe("Tokens: Sets Tab", () => {
   //     tokenThemesSetsSidebar,
   //     tokenSetItems,
   //     tokenSetGroupItems,
-  //   } = await setupFileWithTokens(page);
+  //   } = await setupEmptyTokensFile(page);
```
Comment (EvaMarco) [inline frontend/playwright/ui/specs/tokens.spec.js:238]: This test is commented, why?

File: frontend/src/app/main/ui/workspace/tokens/form.cljs [hunk 4]
```diff
@@ -215,7 +215,9 @@
 (mf/defc form
   {::mf/wrap-props false}
   [{:keys [token token-type action selected-token-set-name]}]
-  (let [token (or token {:type token-type})
+  (let [create? (not (instance? ctob/Token token))
+
```
Comment (EvaMarco) [inline frontend/src/app/main/ui/workspace/tokens/form.cljs]: remove empty line

**Review by EvaMarco — CHANGES_REQUESTED** [review]

File: frontend/playwright/ui/specs/tokens.spec.js (hunk 3 above)
Comment (floscr) [reply frontend/playwright/ui/specs/tokens.spec.js:238]: It was removed during one of the merge conflicts and I search and replaced for this file.
I've added a ticket here to restore it:
https://github.com/tokens-studio/penpot/issues/61

File: frontend/src/app/main/ui/workspace/tokens/form.cljs (hunk 1 above)
Comment (floscr) [reply frontend/src/app/main/ui/workspace/tokens/form.cljs]: This is actually on purpose. I dont want this hook to trigger when the refs update, I only need to trigger it once when editing a token and the tokens have resolved.
Since this should only trigger 
So I want to explicitly want to deps compare the other two refs by reference not by value.

Is there a guideline in penpot when this is the case? Maybe exclude the refs from the deps?

Comment (EvaMarco) [reply frontend/src/app/main/ui/workspace/tokens/form.cljs]: Doing deref on let has nothing to do with deps on effect.
We can save some time doing only one deref, and the as you want, don't place it on deps, so the value change don`t trigger re-render.

Comment (niwinz) [reply frontend/src/app/main/ui/workspace/tokens/form.cljs]: Having state references (state objects) on deps make no sense, deps should almost always have values and no references. We don't need a special guideline, the react use-ref, return a reference that points a value and returns a stable reference, so you never need to put the ref on the deps. The same applies for rumext use-state, because it tries to offer a similar API. 

We have finally applied the change that made the reference returned in rumext use-state always stable, but that broke a behavior in the tokens part that used it in a way that was not recommended. To facilitate progress, we have temporarily reverted this change. So right now the object returned from use-state always changes if the underlying value changes, so use effect will trigger in any way. In other words, having the state reference object on deps and derefing on use-effect has no real meaning and is an anti pattern in any way and we should avoid this because on future we will apply again the change of having stable reference.

TLDR: @EvaMarco suggests derefing once and use many times and is correct

Comment (floscr) [reply frontend/src/app/main/ui/workspace/tokens/form.cljs]: Thank you both for the explanation, I was missing that context :pray: 
I'll update both instances.

Comment (floscr) [reply frontend/src/app/main/ui/workspace/tokens/form.cljs]: @niwinz  Would be neat to add a linter for such things, in [uix](https://github.com/pitch-io/uix/) there's a linter for react hooks to highlight missing dependencies, so it would be possible to lint for deref inside hooks
Linter namespace: https://github.com/pitch-io/uix/blob/master/core/src/uix/linter.clj
Would be super helpful for outside contributors.

Comment (niwinz) [reply frontend/src/app/main/ui/workspace/tokens/form.cljs]: @floscr agree, i will put that on my tasklist, thanks

File: frontend/src/app/main/ui/workspace/tokens/form.cljs (hunk 2 above)
Comment (floscr) [reply frontend/src/app/main/ui/workspace/tokens/form.cljs:407]: This one uses `use-var` for `name-ref` to not re-render on update of the token name input.
I haven't seen any direct deref pattern for `use-var`, is it still applicable?

Comment (EvaMarco) [reply frontend/src/app/main/ui/workspace/tokens/form.cljs:407]: Yes, In that file you have use `@name-ref` 5 times as I can see. 
That is doing `(deref name-ref)` five times each time it renders. 
If we do on let
```clojure
        name-ref* (mf/use-var (:name token))
        name-ref (deref name-ref*)
```
The deref funtion is only executed once. 
Then we will use `name-ref` when we need the value, and name-ref* when we need to set a different value. 

This is appart of use-var, or use-callbacks or deps. We want to reduce "derefs"

Comment (floscr) [reply frontend/src/app/main/ui/workspace/tokens/form.cljs:407]: Okay, thanks :raised_hands:

Comment (floscr) [reply frontend/src/app/main/ui/workspace/tokens/form.cljs:407]: Hmm I'm running into issues with this :thinking: 
The derefed value in the let statement never updates with the suggested changes for the use-var case only.

https://github.com/user-attachments/assets/97c9ebe7-6889-47a1-8850-3f57f3133f16

It's confusing me now also a bit as `use-var` uses a simple wrapper around reacts `useRef` and I would not expect the suggested change to work, but I wasn't sure if I have all the context around rumext.

Am I doing something wrong?

I've pushed some debug commits here:
https://github.com/penpot/penpot/pull/5658/commits/973f58284e6537b88be39d72ba8e7b80c286cf84

Comment (EvaMarco) [reply frontend/src/app/main/ui/workspace/tokens/form.cljs:407]: That’s an error on my part. 
>This one uses use-var for name-ref to not re-render on update of the token name input.
I haven't seen any direct deref pattern for use-var, is it still applicable?
You tell me you where talking about use-var I din't read that. 

You where talking about use-var all the time...... No is not applicable.

Comment (floscr) [reply frontend/src/app/main/ui/workspace/tokens/form.cljs:407]: No problem :relaxed:

**Review by EvaMarco — APPROVED** [review]
