### PR TITLE
Fix several bugs related to interaction overlays

### LINKED ISSUE #2879: bug: prototype interaction position of artboard not respected
### Steps To Reproduce

1. Create a 'main' artboard
2. Create a secondary artboard
3. Add Shadow (to secondary artboard)
image
4. Via prototyping, add an 'interaction' for the artboard (added in step 2), with
- trigger: after delay
- action: open overlay
- destination: secondary artboard (added in step 2)
- position: manual

### Expected behavior

Display overlay on manually set location.

### Actual behavior

Overlay is displayed in wrong location.

### Screenshots or video

Screenshot from 2023-02-01 07-10-30

Screenshot from 2023-02-01 07-07-23

### Desktop (please complete the following information)

- OS: Ubuntu
- Browser: Chromium 109.0.5414.74

### Smartphone (please complete the following information)

_No response_

### Environment (please complete the following information)

- Host: design.penpot.app

### Frontend Stack Trace

_No response_

### Backend Stack Trace

_No response_

### Additional context

This seems to occur because of the added shadow. Seems similar to #2660.

### LINKED ISSUE #3114: bug: positionning of children elements in a flex layout still not good
### Steps To Reproduce

1. Create a flex layout with a button in it
2. Create a 2nd board, serving as "action menu"
3. Create an interaction on the button:
    - open overlay
    - to board 2
    - manual

### Expected behavior

The board 2 is displayed where I place its ghost.

### Actual behavior

The placement of the board 2 makes no sense, it is not related to the interactive button.

### Screenshots or video

Setup:
image

Interaction + ghost placement:
image

Result:
image

### Desktop (please complete the following information)

- Ubuntu 22.04
- Chrome 111

### Smartphone (please complete the following information)

_No response_

### Environment (please complete the following information)

_No response_

### Frontend Stack Trace

_No response_

### Backend Stack Trace

_No response_

### Additional context

Should have been fixed in https://github.com/penpot/penpot/issues/3003 but I still have the issue.

### LINKED ISSUE #3373: bug: Overlay won't close when the interaction is added to a board or text. Works when added to a rectangle.
### Steps To Reproduce

1. Select a screen
2. Connect the screen to another overlay screen (Prototyping)
3. On the overlay screen, select a board / text object and give the 'close overlay' interaction.
4. Prototype the system

### Expected behavior

The overlay should close when clicking the board or the text object

### Actual behavior

The system doesn't close when clicking the respective board or the text.

### Screenshots or video

https://youtu.be/AN1g_tsn5iQ?t=193

You can see it here.

### Desktop (please complete the following information)

- Firefox 114.0.2 on Ubuntu 21.10

### Smartphone (please complete the following information)

_No response_

### Environment (please complete the following information)

Host: design.penpot.app

### Frontend Stack Trace

_No response_

### Backend Stack Trace

_No response_

### Additional context

The overlay closes when the interaction is added to a rectangle object instead of a board or text.

### PR DESCRIPTION
**Pull request by hirunatan**
To merge when all overlays related issues are fixed.

- https://tree.taiga.io/project/penpot/issue/5135
- https://tree.taiga.io/project/penpot/issue/5587
- https://tree.taiga.io/project/penpot/issue/4752
- https://tree.taiga.io/project/penpot/issue/4383

### CODE REVIEW

File: frontend/src/app/main/ui/viewer/shapes.cljs [hunk 1]
```diff
@@ -266,6 +293,9 @@
                 svg-element?       (and (= :svg-raw (:type shape))
                                         (not= :svg (get-in shape [:content :tag])))
 
+                ;; _ (js/console.log "======" (:name shape))
```
Comment (superalex) [inline frontend/src/app/main/ui/viewer/shapes.cljs]: should we remove this comments?

Comment (hirunatan) [reply frontend/src/app/main/ui/viewer/shapes.cljs]: Solved in the last commit.

Comment (superalex) [reply frontend/src/app/main/ui/viewer/shapes.cljs]: Thanks! :)
