### PR TITLE
:bug: Bugfixes

### LINKED ISSUE #1435: pressing [Shift+1] in an empty document causes internal error
**Describe the bug**
pressing [Shift+1] in an empty document causes internal error

**To Reproduce**
1.  open new document
2. press [Shift+1]
3. see  "Internal Error"

**Expected behavior**
zoom set to default state, same as by creation of the document

**Screenshots**
firefox: internal error
Internal Error_20220101105302

chrome: infinite loop
batman_20220101105628

**Desktop (please complete the following information):**

-   OS: Linux
-   Browser: Firefox (different for chrome)
-   Version: latest (web)

**Environment (please complete the following information):**
[x] using SAAS (https://design.penpot.app)

**Frontend Stack Trace (if self-hosted)**

<details>

```
12:02:21.715 Unexpected value Infinity Infinity -Infinity -Infinity parsing viewBox attribute. 2 react-dom.production.min.js:24:234
12:02:22.883
Unhandled Internal Error: d is null errors.cljs:159:7
12:02:22.883
TypeError: d is null
    r$ utils.cljs:51
    jYb actions.cljs:329
    React 11
    unstable_runWithPriority scheduler.production.min.js:19
    nb React
    x helpers.js:77
instrument.js:112:45
12:02:22.894
Unhandled Internal Error: d is null errors.cljs:159:7
12:02:22.895
TypeError: d is null
    r$ utils.cljs:51
    iYb actions.cljs:304
    VQa events.js:768
    SQa events.js:899
    b events.js:296
    x helpers.js:77
    _wrapEventTarget trycatch.js:139
    x instrument.js:479
    OQa events.js:261
    fM events.js:184
    PYb hooks.cljs:41
    vO alpha.cljs:200
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 5
    c alpha.cljs:222
    Zg core.cljs:104
    Zg core.cljs:104
    $h core.cljs:52
    Kd core.cljs:30
    If core.cljs:35
    j core.cljs:871
    pc core.cljs:869
    j core.cljs:4536
    <anonymous> core.cljs:211
    RxJS 16
    next core.cljs:236
    j core.cljs:258
    g store.cljs:56
    mQb shortcuts.cljs:114
    b_a shortcuts.cljs:137
    J mousetrap.js:617
    _handleKey mousetrap.js:678
    handleKey mousetrap.js:1009
    G mousetrap.js:738
```

</details>

### PR DESCRIPTION
**Pull request by EvaMarco**
With this pull request these issues will: 

- Fix crash when pressing Shift+1 on empty file. Close [#1435 ](https://github.com/penpot/penpot/issues/1435)
- Fix typo in Handoff tooltip [Taiga #2428](https://tree.taiga.io/project/penpot/issue/2428).
- Fix line-height and letter-spacing inputs to allow negative values [Taiga #2381](https://tree.taiga.io/project/penpot/issue/2381).
- Fix default project name in all languages [Taiga #2280](https://tree.taiga.io/project/penpot/issue/2280).
- Fix add fill color from the palette to groups and components [Taiga #2313](https://tree.taiga.io/project/penpot/issue/2313).
- Fix Enter as the key action to exit edit path [Taiga #2444](https://tree.taiga.io/project/penpot/issue/2444).

### CODE REVIEW

File: frontend/src/app/main/data/workspace.cljs [hunk 1]
```diff
@@ -634,9 +634,7 @@
             objects (wsh/lookup-page-objects state page-id)
             shapes  (cp/select-toplevel-shapes objects {:include-frames? true})
             srect   (gsh/selection-rect shapes)]
-
-        (if (or (mth/nan? (:width srect))
-                (mth/nan? (:height srect)))
+        (if (= 0 (count shapes))
```
Comment (Alotor) [inline frontend/src/app/main/data/workspace.cljs]: `empty?` is better and faster. Count when is a sequence is quite expensive while `empty?` is always fast (for sequences or vectors)

File: frontend/src/app/main/data/workspace/path/shortcuts.cljs [hunk 2]
```diff
@@ -22,14 +22,8 @@
...
     ptk/WatchEvent
-    (watch [_ state _]
-      ;;  Not interrupt when we're editing a path
-      (let [edition-id (or (get-in state [:workspace-drawing :object :id])
-                           (get-in state [:workspace-local :edition]))
-            path-edit-mode (get-in state [:workspace-local :edit-path edition-id :edit-mode])]
-        (if-not (= :draw path-edit-mode)
-          (rx/of :interrupt (dw/deselect-all true))
-          (rx/empty))))))
+    (watch [_ _ _]
```
Comment (Alotor) [inline frontend/src/app/main/data/workspace/path/shortcuts.cljs]: Please, undo this change because it will break some flows. You still need to check if you're in draw-mode
