### PR TITLE
:bug: Restore viewport and selection when exiting focus mode

### LINKED ISSUE #6820: bug: `toggle-focus-mode` does not restore selection and viewport on exit
### Steps To Reproduce

1. create a file and within it one or several simple shapes
2. select one or a subset of the shapes 
3. toggle on focus mode (e.g. press <kbd>f</kbd>)
4. toggle off focus mode (press again)

### Expected behavior

Upon exiting (toggling off) focus mode, both the selection prior to focusing as well as the viewport should be restored.

Rationale (discussed with designers, see #5720):  
- focus mode represents an excursion into a set of layers of interest. When focus-local work is completed, it should be possible to continue with the task at hand previous to entering focus mode. The selection and viewport represent valuable context to do that.
- focusing in and out should behave like a toggle (an involution), in particular, it should be possible to decide "no, actually let me go back to within the focus, I am not finished". For this decision to take place
  - it should be informed by a wider context than the focus viewport -> importance of restoring previous viewport
  - it should be quick (e.g. upon pressing once more <kbd>f</kbd>) -> importance of restoring initial selection

### Actual behavior

Upon exiting (toggling off) focus mode, the initial viewport (in particular: zoom level) and selection are not preserved 

### Screenshots or video

_No response_

### Desktop (please complete the following information)

- Pop OS! 22.04, Firefox 139.0.4

### Smartphone (please complete the following information)

_No response_

### Environment (please complete the following information)

- local instance (current as of 2025-07-29)
- penpot.app

### Frontend Stack Trace

```console

```

### Backend Stack Trace

```console

```

### Additional context

This is just a description of the observable effects of toggling in and out of focus to provide full context.

- toggle *focus on*

  - how: pressing <kbd>f</kbd> with a selection or via the selection's contextual menu entry *Focus on*
  - effects:

    - viewport:

      - zoom level increases, viewport (roughly?) centers on selection
      - selection is deselected
      - all layers outside of the *focused subtree* are hidden in the viewport
    - layer tree:

      - shows only the selected layer and its children (henceforth *focused subtree*)
      - at top:

        - `<` `layer name` `Focus mode` appear at top
        - all three have *Focus off* behaviour when clicked (see below)
- toggle *focus off*

  - any of repeating <kbd>f</kbd>, pressing the buttons top of the focused layer tree, or selecting the contextual menu option *anywhere*, set the *focus mode* off

    - it's not possible to chain focus modes
  - **the viewport previous to focusing is lost**; instead, the zoom level that focus mode had is kept
  - **there is no selection after toggling in and out of focus**
  - layers outside of the *focus subtree* within the viewport become again visible

### PR DESCRIPTION
**Pull request by alvorithm**
### Related Ticket

fixes #6820 

### Summary

This PR adds code to save viewport and selection information upon entering focus mode into `:workspace-pre-focus`. When the user toggles out of focus mode, the pre-focus state is restored.

It is unclear to me whether saving the entirety of `:workspace-local` into `:workspace-pre-focus` might be too coarse-grained. I believe that, for consistency  map values of `zoom`, `zoom-inverse`, `:selected`, `:vport` and `:vbox` and `:expanded` need this treatment. I am uncertain about `:selrect`. I wonder whether `:last-selected` should not be made to point to the last selected layer *within focus mode*. And I think it's not necessary but possibly harmless to restore `:hide-toolbar`. 

I am nonetheless opening up this PR with the simplified implementation above in order to obtain advice.

### Steps to reproduce 

See #6820. Focusing out now restores selection and viewport, so that `toggle-focus-mode` behaves like an involution (toggle-focus followed by toggle-focus is the identity). 

### Checklist

- [x] Choose the correct target branch; use `develop` by default.
- [X] Provide a brief summary of the changes introduced.
- [X] Add a detailed explanation of how to reproduce the issue and/or verify the fix, if applicable.
- [x] Check CI passes successfully.
- [x] Update the `CHANGES.md` file, referencing the related GitHub issue, if applicable.

### CODE REVIEW

File: frontend/src/app/main/data/workspace/selection.cljs [hunk 1]
```diff
@@ -554,21 +554,34 @@
...
-          (assoc :workspace-focus-selected selected)
-
-          (d/not-empty? (:workspace-focus-selected state))
-          (dissoc :workspace-focus-selected))))
+      (let [selected (dsh/lookup-selected state)
+            have-selection? (d/not-empty? selected)
+            in-mode? (d/not-empty? (:workspace-focus-selected state))]
+
+        (if in-mode?
+          ; exit focus, restoring previous viewport, selection, etc
```
Comment (niwinz) [inline frontend/src/app/main/data/workspace/selection.cljs]: Block comments should be always `;;` (twice `;`)

**Comment by niwinz** [comment]
The solution looks reasonable for me.
