### PR TITLE
:bug: Add export menu to inspect styles tab

### LINKED ISSUE #9660: Export panel missing from the Inspect Styles tab
### Description

The export panel is missing from the Styles tab in the Inspect panel. It is available in the Computed tab but not in Styles, making it impossible to export shapes when viewing the Styles view.

Related: [Taiga #13582](https://tree.taiga.io/project/penpot/issue/13582)

### Steps to reproduce

1. Create a shape on the canvas
2. Open the Inspect tab → Styles
3. The export panel is not visible at the bottom

### Expected behavior

The export panel should appear at the bottom of the Styles tab, same as it does in the Computed tab.

### Affected versions

2.16.0

### PR DESCRIPTION
**Pull request by Xaviju**
### Related Ticket

https://tree.taiga.io/project/penpot/issue/13582

### Summary
Add the export panel to the bottom of the styles tab, same way as it appears and works in the computed tab:   

image

### Steps to reproduce 

- Create a shape in the canvas
- Open the inspect tab -> Styles
- Expect to see the export menu at the bottom
- Export a shape

### Checklist

- [x] Choose the correct target branch; use `develop` by default.
- [x] Provide a brief summary of the changes introduced.
- [x] Add a detailed explanation of how to reproduce the issue and/or verify the fix, if applicable.
- [x] Include screenshots or videos, if applicable.
- [x] Add or modify existing integration tests in case of bugs or new features, if applicable.
- [x] Refactor any modified SCSS files following the refactor guide.
- [x] Check CI passes successfully.
- [x] Update the `CHANGES.md` file, referencing the related GitHub issue, if applicable.

Fixes #9660

### CODE REVIEW

File: frontend/src/app/main/ui/inspect/styles.cljs [hunk 1]
```diff
@@ -89,8 +90,20 @@
       (:type first-shape))
     :multiple))
 
+(def ^:private schema:styles-tab
+  [:map
+   [:format {:optional true} :string] ;; color format, e.g., "hex", "rgba", etc.
```
Comment (EvaMarco) [inline frontend/src/app/main/ui/inspect/styles.cljs]: on keys is called color-space and in schema format. Which one is the right one?

File: frontend/src/app/main/ui/inspect/styles.cljs [hunk 2]
```diff
@@ -131,130 +144,138 @@
...
-          :fill
-          (let [shapes (filter has-fill? shapes)]
-            (when (seq shapes)
-              [:> style-box* {:panel :fill
-                              :shorthand (:fill shorthands)}
-               [:> fill-panel* {:color-space color-space
-                                :shapes shapes
-                                :resolved-tokens resolved-active-tokens
-                                :on-fill-shorthand set-shorthands}]]))
+    [:div {:class (stl/css-case :styles-tab true
```
Comment (EvaMarco) [inline frontend/src/app/main/ui/inspect/styles.cljs]: Is this wrapper needed?.
Add a new line for aria-label

Comment (Xaviju) [reply frontend/src/app/main/ui/inspect/styles.cljs]: This wrapper wraps both the list of properties and the exporter button. I cannot nest the export component into the ordered list.
But, in fact, is a bug, because it must not be a div, but a section container so the aria-label makes sense.

**Review by EvaMarco — APPROVED** [review]
