### PR TITLE
:bug: Fix several bugs

### LINKED ISSUE #9536: Multiple small UI bugs: switch breaks theme modal, tooltip stuck on tab switch, long library names cause scrollbar, and others
### Description

Multiple small UI bugs fixed:

- Switch component breaks the edit theme modal — the switch `id` prop conflicts with the modal's labelled-by association
- Tooltip remains visible on prototype section buttons after switching to another tab
- Long library names cause a scrollbar to appear in the libraries modal when the library has tokens
- The "update library" success message shows incorrect copy
- Console warnings due to missing React key props in component lists

### Steps to reproduce

**Switch breaks theme modal:**
1. Open the themes management modal
2. Toggle any switch component
3. The modal behaves incorrectly due to id conflicts

**Tooltip stuck after tab switch:**
1. Go to the Prototype section
2. Hover over a button to show its tooltip
3. Switch to another tab
4. The tooltip remains visible

**Long library names:**
1. Create a library with a long name
2. Add tokens to the library
3. Open the libraries modal — a horizontal scrollbar appears

### Expected behavior

All UI interactions should work correctly without console warnings or visual glitches.

### Affected versions

2.16.0

### PR DESCRIPTION
**Pull request by EvaMarco**
### Related Ticket

- console warning because lack of key
- https://tree.taiga.io/project/penpot/issue/13639
- https://tree.taiga.io/project/penpot/issue/12924
- https://tree.taiga.io/project/penpot/issue/13534
- https://tree.taiga.io/project/penpot/issue/13627

### Checklist

- [ ] Choose the correct target branch; use `develop` by default.
- [ ] Provide a brief summary of the changes introduced.
- [ ] Add a detailed explanation of how to reproduce the issue and/or verify the fix, if applicable.
- [ ] Include screenshots or videos, if applicable.
- [ ] Add or modify existing integration tests in case of bugs or new features, if applicable.
- [ ] Refactor any modified SCSS files following the refactor guide.
- [ ] Check CI passes successfully.
- [ ] Update the `CHANGES.md` file, referencing the related GitHub issue, if applicable.

Fixes #9536

### CODE REVIEW

File: frontend/src/app/main/ui/workspace/libraries.cljs [hunk 1]
```diff
@@ -440,6 +440,7 @@
                (for [library sample-libraries]
                  [:> sample-library-entry*
                   {:library library
+                   :key (:id library)
```
Comment (niwinz) [inline frontend/src/app/main/ui/workspace/libraries.cljs]: (dm/str ...) 

Keys is better to use strings

**Review by Xaviju — APPROVED** [review]
