### PR TITLE
:bug: Fix color picker

### LINKED ISSUE #3830: bug: eyedropper tool doesn't work
### Steps To Reproduce

From a project with different layers, i'm trying to pick one of the oclors with the eyedropper.

### Expected behavior

The eyedropper should allow me to pick a color from my different layers.

### Actual behavior

They tool's only giving me transparent color, no matter where my pointer is.

### Screenshots or video

image

### Desktop (please complete the following information)

Chrome
Windows 11

### Smartphone (please complete the following information)

_No response_

### Environment (please complete the following information)

_No response_

### Frontend Stack Trace

_No response_

### Backend Stack Trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AzazelN28**
Fix color picker not working

[GitHub Issue #3781](https://github.com/penpot/penpot/issues/3781)

### CODE REVIEW

File: frontend/src/app/main/ui/workspace/viewport/pixel_overlay.cljs [hunk 1]
```diff
@@ -32,22 +32,25 @@
...
+                     (rx/tap (fn [data]
+                               (dom/set-attribute! image "href" data)))
+                     (rx/reduce noop-fn)))))))))
 
 (defn- svg-as-data-url
   "Transforms SVG as data-url resolving any blob, http or https url to
   its data equivalent."
   [svg]
   (let [svg-clone (.cloneNode svg true)]
+    (js/console.log "svg-as-data-url" svg-clone)
```
Comment (superalex) [inline frontend/src/app/main/ui/workspace/viewport/pixel_overlay.cljs]: log! :)

File: frontend/src/app/main/ui/workspace/viewport/pixel_overlay.cljs [hunk 2]
```diff
@@ -167,6 +170,7 @@
            (let [img-node (mf/ref-val img-ref)
                  svg-node (dom/get-element "render")]
              (->> (svg-as-data-url svg-node)
+                  (rx/tap #(js/console.log %))
```
Comment (superalex) [inline frontend/src/app/main/ui/workspace/viewport/pixel_overlay.cljs]: log! :)
