### PR TITLE
:bug: Fix toggling set groups in theme modal not working

### LINKED ISSUE #67: bug: Can't enable/disable theme groups inside themes modal once toggled
### Steps To Reproduce

1. Open theme in themes modal
2. Enable a set group by clicking on the checkbox
3. Disable a set group by clicking on the checkbox
4. Doesnt work

[tokens (4).json](https://github.com/user-attachments/files/18583640/tokens.4.json)

https://github.com/user-attachments/assets/8cc7e318-edbb-4822-90a6-9442a2ebe5d0

### LINKED ISSUE #101: Bug: bug: Cannot rename Design Token Sets when group of same name exists
### Steps To Reproduce

1. Create a set in a group (e.g. `Light / Set 1`
2. Create a set with the group's name (e.g. `Light`)
3. Try to rename the set `Light`

### Expected behavior

The renaming works as usual

### Actual behavior

Renaming stops working if there is a a group with the same name as the set to rename.

### Screenshots or video

https://github.com/user-attachments/assets/e136efa7-f113-4d4d-9799-0cbebc37c9d7

### Desktop (please complete the following information)

Chrome Version 135.0.7049.41 (Official Build) (arm64)

### Smartphone (please complete the following information)

_No response_

### Environment (please complete the following information)

_No response_

### Frontend Stack Trace

```console

```

### Backend Stack Trace

```console

```

### Additional context

_No response_

https://github.com/penpot/penpot/issues/6246

https://tree.taiga.io/project/penpot/issue/10773

### PR DESCRIPTION
**Pull request by floscr**
- Fixes https://github.com/tokens-studio/penpot/issues/67
- Gives theme name autofocus
- Adds integration test for modifying a theme with sets & set groups toggling
- Switches components to new style and converts callbacks to use-fn

### CODE REVIEW

File: frontend/src/app/main/ui/workspace/tokens/sets.cljs [hunk 1]
```diff
@@ -165,6 +165,7 @@
 
     [:div {:ref dref
            :role "button"
+           :aria-label label
```
Comment (floscr) [inline frontend/src/app/main/ui/workspace/tokens/sets.cljs]: Had to add this to get a set group with a label.
Playwright couldn't select only on set groups by the label, I think because the collapse button is also inside before the label.

File: frontend/src/app/main/ui/workspace/tokens/modals/themes.cljs [hunk 2]
```diff
@@ -206,44 +212,56 @@
...
+        on-change-field
+        (mf/use-fn
+         (fn [field value]
+           (swap! theme-state* #(assoc % field value))))
+
+        on-save-form
+        (mf/use-callback
+         (mf/deps theme-state)
+         (fn [e]
+           (js/console.log "theme-state" theme-state)
```
Comment (not-in-stock) [inline frontend/src/app/main/ui/workspace/tokens/modals/themes.cljs]: Looks like a debug leftover

**Comment by not-in-stock** [comment]
LGTM! 🚀

File: frontend/src/app/main/ui/workspace/tokens/modals/themes.cljs [hunk 3]
```diff
@@ -206,44 +212,55 @@
...
+        (mf/use-fn
+         (fn [field value]
+           (swap! theme-state* #(assoc % field value))))
+
+        on-save-form
+        (mf/use-callback
+         (mf/deps theme-state)
+         (fn [e]
+           (dom/prevent-default e)
+           (let [theme (-> @theme-state*
```
Comment (EvaMarco) [inline frontend/src/app/main/ui/workspace/tokens/modals/themes.cljs]: This should be `theme-state`

File: frontend/src/app/main/ui/workspace/tokens/sets.cljs (hunk 1 above)
Comment (EvaMarco) [reply frontend/src/app/main/ui/workspace/tokens/sets.cljs]: You could try "aria-labelledby" and add an ID on the proper label component inside this div.

**Review by EvaMarco — CHANGES_REQUESTED** [review]
Test are not passing.

File: frontend/src/app/main/ui/workspace/tokens/sets.cljs (hunk 1 above)
Comment (floscr) [reply frontend/src/app/main/ui/workspace/tokens/sets.cljs]: Cool didn't know about that one, works!

**Comment by floscr** [comment]
> Test are not passing.

Fixed!

**Review by EvaMarco — APPROVED** [review]
