### PR TITLE
:tada: Feat apply styles to selection

### LINKED ISSUE #9661: Applying text styles to a selection does not work
### Description

Applying text styles (bold, italic, etc.) to a text selection in the editor does not work as expected.

Related: [Taiga #13647](https://tree.taiga.io/project/penpot/task/13647)

### Steps to reproduce

1. Create a text shape
2. Select some text within the shape
3. Try to apply a style (e.g. bold, italic) to the selection

### Expected behavior

The selected text should have the style applied correctly.

### Affected versions

2.16.0

### PR DESCRIPTION
**Pull request by AzazelN28**
### Related Ticket

[Taiga Task #13647](https://tree.taiga.io/project/penpot/task/13647)

### Summary

Apply styles to selection wasn't working.

### Checklist

- [x] Choose the correct target branch; use `develop` by default.
- [x] Provide a brief summary of the changes introduced.
- [x] Check CI passes successfully.

Fixes #9661

### CODE REVIEW

File: render-wasm/src/wasm/text_editor.rs [hunk 1]
```diff
@@ -53,35 +53,53 @@ pub extern "C" fn text_editor_start(a: u32, b: u32, c: u32, d: u32) -> bool {
...
 #[no_mangle]
-pub extern "C" fn text_editor_stop() -> bool {
+pub extern "C" fn text_editor_blur() -> bool {
     with_state_mut!(state, {
-        if !state.text_editor_state.is_active {
+        if !state.text_editor_state.has_focus {
             return false;
         }
-        state.text_editor_state.stop();
+        println!("text_editor_blur");
```
Comment (superalex) [inline render-wasm/src/wasm/text_editor.rs]: ups!

File: render-wasm/src/wasm/text_editor.rs [hunk 2]
```diff
@@ -53,35 +53,53 @@ pub extern "C" fn text_editor_start(a: u32, b: u32, c: u32, d: u32) -> bool {
...
+        state.text_editor_state.blur();
+        println!(
```
Comment (superalex) [inline render-wasm/src/wasm/text_editor.rs]: ups!

File: frontend/src/app/render_wasm/api.cljs [hunk 3]
```diff
@@ -151,17 +162,19 @@
...
-        ;; persisted feature sets in the store state.
-        (when (text-editor-wasm?)
-          (text-editor/text-editor-render-overlay))
+        (text-editor/text-editor-render-overlay)
         ;; Poll for editor events; if any event occurs, trigger a re-render
         (let [ev (text-editor/text-editor-poll-event)]
           (when (and ev (not= ev 0))
+            ;; When StylesChanged, get the current styles.
+            (case ev
+              ;; StylesChanged Event
```
Comment (superalex) [inline frontend/src/app/render_wasm/api.cljs:182]: Shouldn't we have a default case here? 

What about the other posible values?

```
pub enum TextEditorEvent {
    None = 0,
    ContentChanged = 1,
    SelectionChanged = 2,
    StylesChanged = 3,
    NeedsLayout = 4,
}
```

File: frontend/src/app/main/ui/workspace/shapes/text/v3_editor.cljs [hunk 4]
```diff
@@ -312,11 +312,15 @@
      (fn []
        (let [timeout-id (atom nil)
              schedule-blink (fn schedule-blink []
-                              (when (text-editor/text-editor-is-active?)
+                              (when (text-editor/text-editor-has-focus?)
                                 (wasm.api/request-render "cursor-blink"))
                               (reset! timeout-id (js/setTimeout schedule-blink caret-blink-interval-ms)))]
          (schedule-blink)
          (fn []
+           ;; ESTO ES JUSTO LO QUE NO QUIERO, NO QUIERO QUE SE HAGA
```
Comment (superalex) [inline frontend/src/app/main/ui/workspace/shapes/text/v3_editor.cljs]: Probably we should remove this <3

File: frontend/src/app/main/refs.cljs [hunk 5]
```diff
@@ -375,6 +375,9 @@
 (def workspace-modifiers
   (l/derived :workspace-modifiers st/state))
 
+(def workspace-wasm-editor-styles
+  (l/derived :workspace-wasm-editor-styles st/state))
```
Comment (superalex) [inline frontend/src/app/main/refs.cljs:382]: Shouldn't we also dissoc :workspace-wasm-editor-styles in frontend/src/app/main/data/workspace.cljs in the finalize-workspace function?

File: frontend/src/app/main/data/workspace/texts.cljs [hunk 6]
```diff
@@ -249,6 +249,13 @@
   [{:keys [attrs shape]}]
   (shape-current-values shape txt/is-root-node? attrs))
 
+(defn v3-current-text-values
+  [{:keys [editor-styles attrs]}]
+  (let [result (-> editor-styles
+                   (select-keys attrs))
```
Comment (superalex) [inline frontend/src/app/main/data/workspace/texts.cljs:257]: Should we use dm/select-keys?

File: frontend/src/app/render_wasm/api.cljs (hunk 3 above)
Comment (AzazelN28) [reply frontend/src/app/render_wasm/api.cljs:182]: Right now the other posible values are a noop

File: frontend/src/app/main/ui/workspace/shapes/text/v3_editor.cljs (hunk 4 above)
Comment (AzazelN28) [reply frontend/src/app/main/ui/workspace/shapes/text/v3_editor.cljs]: 😅 yup

File: frontend/src/app/main/data/workspace/texts.cljs (hunk 6 above)
Comment (AzazelN28) [reply frontend/src/app/main/data/workspace/texts.cljs:257]: Mmm... I didn't knew there was a macro version of select-keys

File: frontend/src/app/main/refs.cljs (hunk 5 above)
Comment (AzazelN28) [reply frontend/src/app/main/refs.cljs:382]: true
