### PR TITLE
:bug: Fix issue where users can import tokens with invalid characters

### LINKED ISSUE #5: Users can import tokens with invalid characters
- Fix the validation:
  - `$` is only disallowed at the beginning of the token name

- Disallow importing files that dont match our naming specs (from the token form)

Example file: 
- [tokens (6).json](https://github.com/user-attachments/files/18209856/tokens.6.json)

Image

### PR DESCRIPTION
**Pull request by not-in-stock**
# Token Name Validation and Import Restrictions

## Changes Made
- Fixed validation in the token name input to only disallow `$` at the beginning of the token name
- Added restriction to prevent importing files that don't match our token naming specifications (consistent with token form validation)

### Steps to Reproduce
1. Open any token creation form
2. Type a token name with a `$` sign anywhere except the first character (e.g., `foo$bar`)

### Expected Result
- No validation error shown below the input

### Actual Result
- Validation error shown below the input

### Steps to Reproduce
1. Click the `TOOLS` button, then select `Import`
2. Select a file containing tokens with names starting with `$`, for example:
```json
{
  "Global": {
    "$foo": {
      "$value": "#2b9aa6",
      "$type": "color"
    }
  },
  "$themes": [],
  "$metadata": {
    "tokenSetOrder": [
      "Global"
    ]
  }
}
```

### Expected Result
- Toast notification should appear indicating invalid token names

### Actual Result
- File imports successfully without any validation errors

### CODE REVIEW

File: frontend/src/app/main/ui/workspace/tokens/form.cljs [hunk 1]
```diff
@@ -46,14 +46,14 @@
...
-  #"([a-zA-Z0-9-]+\.?)*")
+  #"(?!\$)([a-zA-Z0-9-$]+\.?)*")
 
 (def valid-token-name-schema
   (m/-simple-schema
    {:type :token/invalid-token-name
     :pred #(re-matches valid-token-name-regexp %)
     :type-properties {:error/fn #(str (:value %) " is not a valid token name.
-Token names should only contain letters and digits separated by . characters.")}}))
+Token names should only contain letters and digits separated by . characters and must not start with a $ sign.")}}))
```
Comment (floscr) [inline frontend/src/app/main/ui/workspace/tokens/form.cljs]: Could you move this to the translations file :pray:

**Review by floscr — APPROVED** [review]
Looks good, just a minor comment
