### PR TITLE
:bug: Fix border-radius applied to all corners on token update

### LINKED ISSUE #56: bug: editing a token value modifies other applied border-radius tokens
### Steps To Reproduce

- Create a border-radius token and apply it to one of the corners of a rectangle
- Create a color token and apply it to the fill of the said rectangle
- Edit the color token and change its value to another one

### Expected behavior

The color of the rectangle gets updated.

### Actual behavior

The color of the rectange is updated but the border radius token is now applied to the four corners.
This also happens modifying other types of tokens like rotation, opacity, etc.

### Screenshots or video

https://github.com/user-attachments/assets/0f2ba7e9-e987-435c-b80f-6f2aff0904dc

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Environment (please complete the following information)

_No response_

### Frontend Stack Trace

```console

```

### Backend Stack Trace

```console

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by floscr**
Fixes border radius being overwritten for all corners when updating a token.
Closes https://github.com/tokens-studio/penpot/issues/56

### CODE REVIEW

**Review by not-in-stock — APPROVED** [review]
LGTM!

File: frontend/src/app/main/ui/workspace/tokens/changes.cljs [hunk 1]
```diff
@@ -96,22 +96,24 @@
...
-                      {:reg-objects? true
-                       :ignore-touched true
-                       :attrs ctt/border-radius-keys}))
+(defn update-shape-radius-for-corners [value shape-ids attributes]
+  (ptk/reify ::update-shape-radius-for-corners
+    ptk/WatchEvent
+    (watch [_ _ _]
+      (rx/of
+       ;; NOTE: This key should be namespaced on data tokens, but these events are not there.
+       (ptk/data-event :expand-border-radius)
```
Comment (floscr) [inline frontend/src/app/main/ui/workspace/tokens/changes.cljs]: Is this still necessary?

Comment (hirunatan) [reply frontend/src/app/main/ui/workspace/tokens/changes.cljs]: This is necessary, but it shouldn't be there. Better put it at the calling point (in context-menu). This function is also called from `main.ui.workspace.tokens/update-tokens` and then it's not useful to emit this event, since its done on not selected shapes.

File: frontend/src/app/main/ui/workspace/tokens/changes.cljs [hunk 2]
```diff
@@ -96,22 +96,24 @@
...
-                      (fn [shape]
-                        (when (ctsr/can-get-border-radius? shape)
-                          (ctsr/set-radius-to-single-corner shape (first attributes) value)))
-                      {:reg-objects? true
-                       :ignore-touched true
-                       :attrs ctt/border-radius-keys}))
+(defn update-shape-radius-for-corners [value shape-ids attributes]
+  (ptk/reify ::update-shape-radius-for-corners
+    ptk/WatchEvent
+    (watch [_ _ _]
```
Comment (hirunatan) [inline frontend/src/app/main/ui/workspace/tokens/changes.cljs]: Why are you changing this from a simple function into an event?

File: frontend/src/app/main/ui/workspace/tokens/changes.cljs [hunk 3]
```diff
@@ -96,22 +96,24 @@
 (defn update-shape-radius-all [value shape-ids]
   (dwsh/update-shapes shape-ids
                       (fn [shape]
-                        (when (ctsr/can-get-border-radius? shape)
-                          (ctsr/set-radius-to-all-corners shape value)))
+                        (ctsr/set-radius-to-all-corners shape value))
```
Comment (hirunatan) [inline frontend/src/app/main/ui/workspace/tokens/changes.cljs:99]: Why do you remove the check? Are you sure this can only be called for shapes that may have border radius?

Comment (floscr) [reply frontend/src/app/main/ui/workspace/tokens/changes.cljs:99]: Because these functions are already checking this:
https://github.com/tokens-studio/penpot/blob/430c5cd60206930e22742f6c342baa52bb721f34/common/src/app/common/types/shape/radius.cljc#L40-L58

File: frontend/src/app/main/ui/workspace/tokens/changes.cljs (hunk 2 above)
Comment (floscr) [reply frontend/src/app/main/ui/workspace/tokens/changes.cljs]: No real reason, I thought it would be better everything is uniform in this ns

File: frontend/src/app/main/ui/workspace/tokens/changes.cljs (hunk 1 above)
Comment (floscr) [reply frontend/src/app/main/ui/workspace/tokens/changes.cljs]: Yeah I'll move it in this PR then :+1:

File: frontend/src/app/main/ui/workspace/tokens/changes.cljs (hunk 3 above)
Comment (hirunatan) [reply frontend/src/app/main/ui/workspace/tokens/changes.cljs:99]: ok

File: frontend/src/app/main/ui/workspace/tokens/changes.cljs (hunk 2 above)
Comment (hirunatan) [reply frontend/src/app/main/ui/workspace/tokens/changes.cljs]: I don't understand this. All `update-xxx` functions are normal functions that return an event, not events theirselves.  I think this should be rolled back.

File: frontend/src/app/main/ui/workspace/tokens/context_menu.cljs [hunk 4]
```diff
@@ -179,14 +180,24 @@
                               :on-update-shape wtch/update-layout-sizing-limits}
                              context-data)))
 
+(defn update-shape-radius-all [value shape-ids]
+  (st/emit!
+   (ptk/data-event ::expand-border-radius)
```
Comment (hirunatan) [inline frontend/src/app/main/ui/workspace/tokens/context_menu.cljs]: I think there is no need to expand here. This causes event that the border radius input expands to have four values. But if we set the same value of all borders it should be kept collapsed.

File: frontend/src/app/main/ui/workspace/tokens/changes.cljs (hunk 2 above)
Comment (floscr) [reply frontend/src/app/main/ui/workspace/tokens/changes.cljs]: If you look at the functions below, it's a mixture of events and update functions:
https://github.com/tokens-studio/penpot/blob/6e641b2dd5c1c438d2713970684ed8ab47d50e06/frontend/src/app/main/ui/workspace/tokens/changes.cljs#L149-L202

Anyway I'm fine with either way

File: frontend/src/app/main/ui/workspace/tokens/context_menu.cljs (hunk 4 above)
Comment (floscr) [reply frontend/src/app/main/ui/workspace/tokens/context_menu.cljs]: Ok I misunderstood what this does, I thought it would be some kind of data collection event.
In that case these should also not be `::`

**Review by hirunatan — APPROVED** [review]
