### PR TITLE
Bugfixing

### LINKED ISSUE #837: blending doesn't work for layers with a shadow applied
**Describe the bug**
blending doesn't work for layers with a shadow applied

**Screenshots**

Captura de pantalla 2021-04-13 15 37 32

**Desktop (please complete the following information):**

-   OS: macOS 10.15.7
-   Browser: Firefox 88.0b9 (64-bit)

**Environment (please complete the following information):**
Using SAAS

### LINKED ISSUE #845: Selection indicator too bold
Selection indicator is too bold if you select shapes with 1px border.

selected_vector_shape

### LINKED ISSUE #856: Not possible to reach menu of last file in projects overview
**Describe the bug**
The menu of the last file in the projects overview opens downwards and is thus inaccessible:

**To Reproduce**
1.  Create at least a few projects
2.  Have one file in each
3.  Try to open the menu of a file which is at the bottom of the viewport
4.  Be unable to actually interact with the options

**Expected behavior**
Some options there:
- The nicest in my view is to have some whitespace at the end of this list by default. That way the last row of entries doesn’t stick to the bottom of the screen but can scroll a bit up towards the middle. This is often done in text editors too.
- The menu could open upwards
- As soon as the menu opens, whitespace can be inserted – worst solution since then you have to realize that it did this, and scroll

**Screenshots**
impossible to reach menu of last item

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04
-   Browser: Firefox
-   Version: 87

**Environment (please complete the following information):**
Using https://design.penpot.app

### LINKED ISSUE #859: Counter in team settings shows wrong (negative) number
**Describe the bug**
Even though we have 3 projects (and 1 drafts section) where 2 projects have 1 file each, in the settings it shows "-1 projects".

**To Reproduce**
No idea to be honest, has always been this way though.

**Expected behavior**
Shows the correct number of projects. ;)

**Screenshots**
confusing icon

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04
-   Browser: Firefox
-   Version: 87

**Environment (please complete the following information):**
Using https://design.penpot.app

### PR DESCRIPTION
**Pull request by Alotor**
- Fix problems with blending modes [#837](https://github.com/penpot/penpot/issues/837)
- Fix problem with zoom an selection rect [#845](https://github.com/penpot/penpot/issues/845)
- Fix problem displaying team statistics [#859](https://github.com/penpot/penpot/issues/859)
- Fix problems with text editor selection [Taiga #1546](https://tree.taiga.io/project/penpot/issue/1546)
- Fix problem when opening the context menu in dashboard at the bottom [#856](https://github.com/penpot/penpot/issues/856)
- Fix visual problem with group invite [Taiga #1290](https://tree.taiga.io/project/penpot/issue/1290)
- Fix issues with promote owner panel [Taiga #763](https://tree.taiga.io/project/penpot/issue/763)
- Allow use library colors when defining gradients [Taiga #1614](https://tree.taiga.io/project/penpot/issue/1614)

Closes #837
Closes #845
Closes #859
Closes #856

### CODE REVIEW

File: frontend/src/app/main/ui/workspace/viewport/selection.cljs [hunk 1]
```diff
@@ -255,7 +255,6 @@
                            :zoom zoom
                            :color color
                            :on-move-selected on-move-selected}]
-       [:& outline {:shape shape :color color}]
```
Comment (hirunatan) [inline frontend/src/app/main/ui/workspace/viewport/selection.cljs:258]: We can remove the import of out line, don't we?
