### PR TITLE
Alotor bugfixing 8

### LINKED ISSUE #3941: bug: Selecting from Color Palette does not work for board when there is no existing fill
### Steps To Reproduce

1. Create a board
2. Open color palette (if not open already)
3. Try to select a color

### Expected behavior

Selecting a color should create a fill of the selected color in the board.

### Actual behavior

No color is selected. If a fill is manually created from the side panel, it is then possible to select colors using the color palette. 
For rectangles and ellipses there is no need to create a fill manually first, partly because they start with a fill by default, but even if you delete the fill on a rectangle or ellipse selecting a color from the color palette still works. If boards worked like rectangles and ellipses it would remove one step from selecting the desired color for a board which would improve usability.

### Screenshots or video

_No response_

### Desktop (please complete the following information)

Windows 10, Firefox 121.0

### Smartphone (please complete the following information)

_No response_

### Environment (please complete the following information)

https://design.penpot.app

### Frontend Stack Trace

_No response_

### Backend Stack Trace

_No response_

### Additional context

_No response_

### LINKED ISSUE #3998: bug: Adding vector path points before first point of existing open path not working
### 1. Draw an open vector path
image

### 2. Start editing the path from the other end, i.e. start from the first point (top left in the example)
image

### 3. After adding one point, the path tool resets so that path drawing continues from the last point
image

### Expected behavior

The path editing should continue from the previous point drawn
image

### Actual behavior

The path editing continues from the original "last point" drawn in the path
image

### Screenshots or video

_No response_

### Desktop (please complete the following information)

macOS Monterey 12.7.2 - Firefox 120.0.1

### Smartphone (please complete the following information)

_No response_

### Environment (please complete the following information)

- Replicated on design.penpot.app 1.19.4-10723-gdce2eb03c
- Replicated on grid preview build on penpot.app 1.21.0-12037-g470cf0813

### Frontend Stack Trace

_No response_

### Backend Stack Trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Alotor**
https://tree.taiga.io/project/penpot/issue/6603
https://tree.taiga.io/project/penpot/issue/6600
https://tree.taiga.io/project/penpot/issue/6596
https://tree.taiga.io/project/penpot/issue/6593
https://tree.taiga.io/project/penpot/issue/6464
https://tree.taiga.io/project/penpot/issue/6372
https://tree.taiga.io/project/penpot/issue/5907

### CODE REVIEW

File: frontend/src/app/main/data/workspace/colors.cljs [hunk 1]
```diff
@@ -428,10 +427,7 @@
                 result
                 (let [cur (first pending)
                       ;; We treat frames that aren't components and with no fill the same as groups
```
Comment (hirunatan) [inline frontend/src/app/main/data/workspace/colors.cljs]: REmove this comment, no longer true (I'll do it myself)
