### PR TITLE
:bug: Fix multiple selection on shapes with token applied to stroke-color

### LINKED ISSUE #9522: Multiple issues with token-applied stroke colors, color selection, page deletion, and sidebar layout
## Summary

When multiple shapes are selected that have tokens applied to their stroke colors, the stroke properties panel displays incorrectly and does not show the expected "multiple values" indicator. Additionally, related issues exist with token color filtering in the color selection panel, page deletion in the sitemap, and a layout issue in the left header.

## Problem

1. **Stroke panel shows incorrect state on multi-selection** — When multiple shapes with different token-applied stroke colors are selected, the stroke panel does not display the "multiple values" state. It fails to check the `applied-tokens` map for `:stroke-color` and `:stroke-width` having `:multiple` values, so it shows a single color or erroneous state instead.

2. **Token color filtering is incorrect** — The color selection panel's token color filter (`filterv :token-name`) was matching colors that also have a `:ref-id` (library colors that happen to have a token applied), leading to incorrect categorization of colors into library-colors, token-colors, and plain colors.

3. **Sitemap page deletion triggers navigation** — Clicking the delete button on a page in the sitemap was not stopping event propagation, so the click could bubble up and trigger unintended navigation to that page before the delete confirmation appeared.

4. **Left header layout overflow** — The `.project-tree` element in the left header lacks `flex-shrink` and `min-width` constraints, causing layout overflow in certain sidebar configurations.

## Steps to Reproduce

1. Create two or more shapes and apply different stroke color tokens to each.
2. Select all the shapes simultaneously.
3. Open the stroke properties panel — observe it shows incorrect state instead of the "multiple values" indicator.

## Expected Behavior

When multiple shapes with distinct token-applied stroke colors are selected, the stroke panel should show the "multiple values" indicator. Color selection should correctly separate library colors, token colors, and plain colors. Page deletion should not trigger navigation. The left header layout should not overflow.

## Related

- PR: #9110

### PR DESCRIPTION
**Pull request by EvaMarco**
## Related Issue

Fixes #9522

## Summary

When multiple shapes are selected that have tokens applied to their stroke colors, the stroke properties panel displays incorrectly and does not show the expected "multiple values" indicator.

## Changes

- **Stroke panel multi-selection fix** — Added checks for `:stroke-color` and `:stroke-width` in `applied-tokens` having `:multiple` values, so the panel correctly shows the "multiple values" state when shapes with distinct token-applied stroke colors are selected together.
- **Token color filtering fix** — Fixed `color_selection.cljs` to properly separate library colors, token colors, and plain colors by excluding token colors from the library color filter.
- **Sitemap page deletion fix** — Added `dom/stop-propagation` to the delete page handler to prevent unintended navigation when clicking the delete button.
- **Left header layout fix** — Added `flex-shrink: 1` and `min-width: 0` to `.project-tree` to prevent layout overflow.

## Steps to Reproduce

1. Create two or more shapes and apply different stroke color tokens to each.
2. Select all the shapes simultaneously.
3. Open the stroke properties panel — observe it shows incorrect state instead of the "multiple values" indicator.

### CODE REVIEW

File: frontend/src/app/main/ui/workspace/sidebar/options/menus/color_selection.cljs [hunk 1]
```diff
@@ -103,16 +107,18 @@
         (mf/with-memo [file-id shapes libraries]
           (prepare-colors shapes file-id libraries))
 
+        ;; _ (prn "color-selection-menu*")
```
Comment (niwinz) [inline frontend/src/app/main/ui/workspace/sidebar/options/menus/color_selection.cljs]: 🔥

File: frontend/src/app/main/ui/workspace/sidebar/options/menus/color_selection.cljs [hunk 2]
```diff
@@ -69,12 +69,16 @@
...
 
-        ;; Split into: library colors, token colors, and plain colors
-        library-colors (filterv :ref-id all-colors)
+        ;; ;; Split into: library colors, token colors, and plain colors
+        ;; library-colors (filterv :ref-id all-colors)
+        ;; token-colors   (filterv :token-name all-colors)
+        ;; colors         (filterv #(and (nil? (:ref-id %))
+        ;;                               (not (:token-name %)))
+        ;;                         all-colors)
+
```
Comment (niwinz) [inline frontend/src/app/main/ui/workspace/sidebar/options/menus/color_selection.cljs]: :fire:
