### PR TITLE
:bug: Update padding only on shapes with layout

### LINKED ISSUE #59: bug: Internal error when applying not accepted tokens
### Steps To Reproduce

- Create a dimension token.
- Create a board.
- Apply the dimension token to the left padding of the board.
- An internal error occurs.

### Expected behavior

This happens because boards do not have a "padding" property (unless they are converted to a layout).

This issue will be addressed in the enhancement described here: [GitHub Issue](https://github.com/tokens-studio/penpot/issues/8). However, if it's not possible to resolve it for the MVP, we should at least avoid throwing an internal error and simply not apply the token instead.

### Actual behavior

- An internal error occurs.

[report (9).txt](https://github.com/user-attachments/files/18522051/report.9.txt)

### Screenshots or video

_No response_

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Environment (please complete the following information)

_No response_

### Frontend Stack Trace

```console

```

### Backend Stack Trace

```console

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by floscr**
Fixes https://github.com/tokens-studio/penpot/issues/59 and adds test case for padding

### CODE REVIEW

File: frontend/src/app/main/ui/workspace/tokens/changes.cljs [hunk 1]
```diff
@@ -173,22 +174,30 @@
                        (zipmap (repeat value)))]
     {:layout-gap layout-gap}))
 
+(defn shape-ids-with-layout [state shape-ids]
```
Comment (niwinz) [inline frontend/src/app/main/ui/workspace/tokens/changes.cljs]: Should be marked as private as this function is only used here. It helps detect unused functions when they become unused thanks to linter.
