### PR TITLE
:bug: Fix shared button variant and title

### LINKED ISSUE #9541: Wrong button label on published library with no assets in the assets panel
### Description

The "Add library" / "Manage library" button in the assets panel shows the wrong label when a library has been published but contains no assets. It displays "Add library" instead of "Manage library", which is confusing because the library is already published.

### Steps to reproduce

1. Create a file
2. Go to the Assets tab (creating no components)
3. Click "Add library" and publish it
4. Click "Publish" again on the "Publish empty library" modal
5. Switch to the Layers tab
6. Go back to the Assets tab

### Expected behavior

- If the library is already published → show "Manage library" regardless of whether it has components
- If the library is not published with components → "Manage library"
- If the library is not published with no components → "Add library"

### Affected versions

2.16.0

### PR DESCRIPTION
**Pull request by EvaMarco**
### Related Ticket
This PR solves this issue https://tree.taiga.io/project/penpot/issue/13730

### Checklist

- [ ] Choose the correct target branch; use `develop` by default.
- [ ] Provide a brief summary of the changes introduced.
- [ ] Add a detailed explanation of how to reproduce the issue and/or verify the fix, if applicable.
- [ ] Include screenshots or videos, if applicable.
- [ ] Add or modify existing integration tests in case of bugs or new features, if applicable.
- [ ] Refactor any modified SCSS files following the refactor guide.
- [ ] Check CI passes successfully.
- [ ] Update the `CHANGES.md` file, referencing the related GitHub issue, if applicable.

Fixes #9541

### CODE REVIEW

File: frontend/src/app/main/ui/workspace/sidebar/assets.cljs [hunk 1]
```diff
@@ -90,6 +90,7 @@
         libs           (mf/deref refs/libraries)
         num-libs       (count libs)
         file           (get libs file-id)
+        shared?     (:is-shared file)
```
Comment (niwinz) [inline frontend/src/app/main/ui/workspace/sidebar/assets.cljs]: Please, fix this indentation

**Review by niwinz — CHANGES_REQUESTED** [review]

**Review by niwinz — APPROVED** [review]
